const express = require('express');
const router = express.Router();
const { createFood, updateFood, searchFood, getFoodByBarcode, getUserFoods, deleteFood } = require('../controllers/foodController');
const { protect } = require('../middleware/auth');
router.use(express.json());
router.use(protect);
router.get('/search', searchFood);
router.get('/my', getUserFoods);
router.get('/barcode/:barcode', getFoodByBarcode);
router.post('/', createFood);
router.put('/:id', updateFood);
router.delete('/:id', deleteFood);
module.exports = router;